[package]
name = "karaoke"
version = "0.1.0"
authors = ["TonalidadeHidrica <47710717+TonalidadeHidrica@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.2"
dasp = "0.11.0"
derive_more = "0.99.11"
druid = { version = "0.7.0", features = ["im"] }
itertools = "0.10.0"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.14"
thiserror = "1.0.24"

[patch.crates-io]
im = { git = "https://github.com/arthurprs/im-rs", branch = "fix" }
